run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*_generated\\.go$"
    - ".*_test\\.go$"
